### ISSUE TITLE
Bug: stdout is not captured if code is launched via desktop entry

### ISSUE THREAD

**Issue by theironrobin** [BOJIT/btmgmt#5]
Steps to reproduce:

1. Install [this python wrapper](https://gist.github.com/alexr4535/9ba276fe07974ad072b370d666447d43) to /usr/local/bin
2. Install [this desktop entry](https://gist.github.com/alexr4535/34cf6ab91420eaae0dec6a4754f14fd9) to /usr/local/share/applications
3. open terminal, `btmgmt_wrapper -c info` will update ~/py-btmgmt.out with correct stdout
4. launch "btmgmt wrapper" with an application launcher, will update ~/py-btmgmt.out with empty string

**Comment by BOJIT** [comment]
Hi,
My main dev machine doesn't run Linux, and all my Linux machines run headless, so I have no way of testing this.

That said, the reason this is probably happening is because `gdm` redirects `stdout` and `stderr` somewhere else at launch:
https://superuser.com/questions/606985/any-way-to-view-stdout-of-a-program-after-it-has-been-started-in-gnome-shell

This library uses the macros `STDOUT_FILENO` and `STDERR_FILENO` from `<unistd.h>`, so if the streams have already been redirected, these file descriptors will point at the wrong stream. A simple fix is to replace all instances of `STDOUT_FILENO` and `STDERR_FILENO` with `fileno(stdout)` and `fileno(stderr)` in the file `btmgmt_wrapper.c`.

I don't want to do this if possible, as it makes the library specific to `glibc`, but if you test it and it sorts out your problem I'll change it.

For initial debugging, just try using the `command` function rather than `command_str` and see if the output string shows up in `journalctl`. If it does, that tells you it's a redirection issue.

Best of luck,
James

**Comment by theironrobin** [comment]
journalctl output upon launching "btmgmt wrapper"

> Mar 26 15:43:14 mercury systemd[1452]: Started Application launched by gnome-shell.
> Mar 26 15:43:14 mercury systemd[1452]: app-gnome-wrapper-181267.scope: Succeeded.

So not seeing the stdout expected here.

**Comment by BOJIT** [comment]
Hmm, if even the stdout from the `command` function is not showing up in the logs then the issue must be outside the scope of this library (the actual `stdout` printing is handled by the submoduled BlueZ stack). However if `command` shows up and `command_str` doesn't, that is a library issue that I can address.

**Comment by theironrobin** [comment]
Yeah, not seeing any output in journalctl using either function.

**Comment by BOJIT** [comment]
Presumably do the library functions (`power on`, `bredr off`, etc...) work?

If they do and there is no console output for any of the functions then I don't think it can be a library issue. The `btmgmt` tool will output to `stdout` regardless of whether it's called through this wrapper or not. It might be worth just trying some basic print statements in both your python code and in the c driver to see what actually gets logged.

I'm going to mark this as closed for now, but if you do find any library-specific problems that need to be addressed feel free to re-open.

**Comment by theironrobin** [comment]
Yes printing something like "Hello World" works and shows up in journalctl. Thanks for the help anyway. I might just have to keep depending on the btmgmt binary
